"""Add breed

Revision ID: 5f97c3893950
Revises: d5eec431d315
Create Date: 2023-11-26 18:14:09.874437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f97c3893950'
down_revision: Union[str, None] = 'd5eec431d315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dogs', sa.Column('breed', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dogs', 'breed')
    # ### end Alembic commands ###
